#!/bin/sh

set -e

update-alternatives --install /usr/lib/x86_64-linux-gnu/libblas.so libblas.so-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/atlas/libblas.so 35 \
                    --slave /usr/lib/x86_64-linux-gnu/libblas.a libblas.a-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/atlas/libblas.a \
                    --slave /usr/include/x86_64-linux-gnu/cblas.h cblas.h-x86_64-linux-gnu \
                    /usr/include/x86_64-linux-gnu/cblas-atlas.h \
                    --slave /usr/lib/x86_64-linux-gnu/pkgconfig/blas.pc \
                    blas.pc-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/pkgconfig/blas-atlas.pc

update-alternatives --install /usr/lib/x86_64-linux-gnu/liblapack.so \
                    liblapack.so-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/atlas/liblapack.so 35 \
                    --slave /usr/lib/x86_64-linux-gnu/liblapack.a liblapack.a-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/atlas/liblapack.a \
                    --slave /usr/lib/x86_64-linux-gnu/pkgconfig/lapack.pc \
                    lapack.pc-x86_64-linux-gnu \
                    /usr/lib/x86_64-linux-gnu/pkgconfig/lapack-atlas.pc



exit 0
